export const POSTURE_CAPTURE_CONFIG = {
  package: {
    name: '@mediapipe/tasks-vision',
    version: '0.10.35',
  },
  runtime: {
    targetInferenceFps: 10,
    minInferenceFps: 8,
    maxInferenceFps: 12,
    mainThreadFallbackFps: 4,
    performanceWindowMs: 3_000,
    fullPerformanceWarningFps: 8,
    maxLatencySamples: 600,
  },
  quality: {
    visibilityThreshold: 0.65,
    presenceThreshold: 0.65,
    edgeMargin: 0.035,
    minBodyHeightRatio: 0.55,
    maxBodyHeightRatio: 0.9,
    maxCenterOffset: 0.1,
    frontMinSpanToTorsoRatio: 0.55,
    sideMaxSpanToTorsoRatio: 0.35,
    stanceCalibrationDurationMs: 10_000,
    stanceCalibrationMaxSampleGapMs: 1_000,
    stanceCalibrationThresholdFactor: 0.9,
    minimumMeanLuma: 55,
    minimumSharpness: 40,
    sharpnessNormalizationCeiling: 200,
    stabilityWindowMs: 1_000,
    stabilityMaxTorsoNormalizedDelta: 0.18,
    minimumStabilitySamples: 3,
  },
  capture: {
    qualifyingDurationMs: 1_500,
    countdownDurationMs: 3_000,
    captureDurationMs: 4_000,
    candidateSampleIntervalMs: 200,
    maxCandidates: 5,
    maxCandidateBlobBytes: 1.5 * 1024 * 1024,
    maxTotalCandidateBytes: 6 * 1024 * 1024,
    maxCandidateWidth: 960,
    maxCandidateHeight: 1280,
    candidateMimeType: 'image/webp',
    candidateQuality: 0.82,
    scoreWeights: {
      completeness: 0.35,
      landmarkReliability: 0.3,
      sharpness: 0.2,
      stability: 0.15,
    },
  },
  model: {
    fullPath: '/models/posture/pose_landmarker_full.task',
    litePath: '/models/posture/pose_landmarker_lite.task',
    minPoseDetectionConfidence: 0.65,
    minPosePresenceConfidence: 0.65,
    minTrackingConfidence: 0.65,
  },
} as const;

export type PostureCaptureConfig = typeof POSTURE_CAPTURE_CONFIG;
