import type { StrengthTrend } from '../../types/growth';
import TrendChart from './TrendChart';

export default function StrengthTrendCard({ trends, selectedId, onSelect }: { trends: StrengthTrend[]; selectedId: string; onSelect: (id: string) => void }) {
  if (trends.length === 0) return <section className="rounded-[24px] border border-lime-300/20 bg-[#111611]/95 p-5"><h2 className="text-xl font-black">力量趋势</h2><div className="py-10 text-center"><p className="font-bold text-zinc-300">暂无力量记录</p><p className="mt-2 text-sm text-zinc-500">记录动作重量或身体数据后，这里会显示真实趋势。</p></div></section>;
  const trend = trends.find(({ exerciseId }) => exerciseId === selectedId) ?? trends[0];
  const latest = trend.points.at(-1);
  const chartPoints = trend.points.map((point) => ({ label: point.date.slice(5).replace('-', '/'), value: point.value, detail: tooltip(point, trend.weightType) }));
  return <section className="rounded-[24px] border border-lime-300/20 bg-[#111611]/95 p-5"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-black">力量趋势</h2><label className="relative"><span className="sr-only">选择动作</span><select value={trend.exerciseId} onChange={(event) => onSelect(event.target.value)} className="min-h-10 max-w-[9rem] rounded-full border border-white/10 bg-black/30 px-3 !text-white">{trends.map((item) => <option key={item.exerciseId} value={item.exerciseId}>{item.label}</option>)}</select></label></div>{trend.status === 'empty' ? <div className="py-10 text-center"><p className="font-bold text-zinc-300">暂无重量记录</p>{trend.missingBodyWeightCount ? <p className="mt-2 text-sm text-amber-200">缺少对应体重记录</p> : null}</div> : <><div className="mt-6"><p className="text-sm text-zinc-400">最高有效重量</p><p data-testid="strength-current-value" className="mt-2 text-[2.4rem] font-black tracking-[-0.04em] text-lime-300">{format(latest!.value)} <span className="text-base">kg</span></p>{latest?.reps ? <p className="mt-2 text-sm text-zinc-400">{latest.reps} 次 · 第 {latest.setIndex} 组</p> : null}</div>{trend.status === 'single' ? <p className="mt-7 rounded-xl bg-white/[0.035] p-4 text-center text-sm text-zinc-400">再记录一次即可生成趋势</p> : <div className="mt-4"><TrendChart id={`strength-${trend.exerciseId}`} points={chartPoints} label={`${trend.label}有效重量趋势`} /></div>}</>}</section>;
}

function tooltip(point: StrengthTrend['points'][number], weightType: StrengthTrend['weightType']) { const parts = [point.date]; if (point.bodyWeight !== undefined) parts.push(`体重 ${format(point.bodyWeight)}kg`); if (point.modifierWeight !== undefined) parts.push(`${weightType === 'bodyweight_assisted' ? '助力' : '额外负重'} ${format(point.modifierWeight)}kg`); parts.push(`有效重量 ${format(point.value)}kg`); if (point.reps) parts.push(`${point.reps}次`); return parts.join(' · '); }
function format(value: number) { return Number.isInteger(value) ? String(value) : value.toFixed(1); }
